---
name: Aalen Veranstaltungen Converter

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-sync requirements.txt
      - name: 🚀 Run script
        run: python3 fetch.py aalen.ics
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: aalen.ics
          author_name: Github Actions
          author_email: actions@github.com
          message: add changes
